baseURL = "https://tachunwu.github.io/"
languageCode = "en-us"
title = "tachunn labs"
theme="archie"
copyright = "© tachunn"
publishdir = "./public/"


# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="light"
	useCDN=false
#	subtitle = "film/code/trippy/hyponotic"

# Social Tags

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3
